# Generated by Django 3.2.9 on 2023-05-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentAndDelivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Delivery_fee',
        ),
    ]
