# Generated by Django 3.2.9 on 2023-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_image1', models.ImageField(upload_to='website_interface')),
                ('one_image2', models.ImageField(upload_to='website_interface')),
                ('one_image3', models.ImageField(upload_to='website_interface')),
                ('two_image1', models.ImageField(upload_to='website_interface')),
                ('two_image2', models.ImageField(upload_to='website_interface')),
                ('two_image3', models.ImageField(upload_to='website_interface')),
                ('three_image1', models.ImageField(upload_to='website_interface')),
                ('three_image2', models.ImageField(upload_to='website_interface')),
                ('three_image3', models.ImageField(upload_to='website_interface')),
                ('four_image1', models.ImageField(upload_to='website_interface')),
                ('four_image2', models.ImageField(upload_to='website_interface')),
                ('four_image3', models.ImageField(upload_to='website_interface')),
            ],
        ),
        migrations.DeleteModel(
            name='Four_IndexImageGroup',
        ),
        migrations.DeleteModel(
            name='One_IndexImageGroup',
        ),
        migrations.DeleteModel(
            name='Three_IndexImageGroup',
        ),
        migrations.DeleteModel(
            name='Two_IndexImageGroup',
        ),
    ]
