# Generated by Django 3.2.9 on 2023-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Interface', '0002_auto_20230601_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_imagegroup',
            name='four_image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='four_image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='four_image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='one_image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='one_image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='one_image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='three_image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='three_image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='three_image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='two_image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='two_image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
        migrations.AlterField(
            model_name='index_imagegroup',
            name='two_image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='website_interface'),
        ),
    ]
