# Generated by Django 3.2.9 on 2023-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Interface', '0003_auto_20230601_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_image1', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('one_image2', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('two_image1', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('two_image2', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('three_image1', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('three_image2', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('four_image1', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('four_image2', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('five_image1', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
                ('five_image2', models.ImageField(blank=True, default=None, null=True, upload_to='website_interface')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
