# Generated by Django 3.2.9 on 2023-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Interface', '0005_auto_20230601_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='buy_more_mart_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
