# Generated by Django 3.2.9 on 2023-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Interface', '0006_info_buy_more_mart_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='messenger_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
