# Generated by Django 3.2.9 on 2023-05-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20230514_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_image'),
        ),
    ]
