# Generated by Django 3.2.9 on 2023-05-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_delivery_payment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Payment_type',
        ),
    ]
