# Generated by Django 3.2.9 on 2023-05-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_auto_20230521_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
