# Generated by Django 3.2.9 on 2023-05-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total_items',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
