# Generated by Django 3.2.9 on 2023-05-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20230522_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_member',
        ),
        migrations.AddField(
            model_name='order',
            name='each_product',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
