# Generated by Django 3.2.9 on 2023-05-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20230523_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='each_product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total_price',
            field=models.IntegerField(help_text='ပစ္စည်းအားလုံး နှင့် Delivery fee စုစုပေါင်းကျသင့်ငွေ'),
        ),
    ]
