# Generated by Django 3.2.9 on 2023-05-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_auto_20230514_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.category'),
        ),
    ]
