# Generated by Django 3.2.9 on 2023-05-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_product_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Application.category'),
        ),
    ]
